services:

  firewall:
    image: debian
    privileged: true
    container_name: firewall
    command: >
      bash -c "
        apt update &&
        apt install -y iptables iproute2 &&
        iptables -F &&
        iptables -P INPUT DROP &&
        iptables -P FORWARD DROP &&
        iptables -P OUTPUT ACCEPT &&
        iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT &&
        iptables -A INPUT -p tcp --dport 22 -j ACCEPT &&
        iptables -A INPUT -p tcp --dport 80 -j ACCEPT &&
        iptables -A INPUT -p tcp --dport 443 -j ACCEPT &&
        iptables -A INPUT -p tcp --dport 389 -j ACCEPT &&
        tail -f /dev/null"
    networks:
      server_network:
        ipv4_address: 172.50.0.10
      client_network:
        ipv4_address: 172.51.0.10

  dns: 
    image: ubuntu/bind9
    container_name: dns_server
    networks:
      server_network:
        ipv4_address: 172.50.0.11
    volumes:
      - ./DNS/named.conf.local:/etc/bind/named.conf.local
      - ./DNS/named.conf.options:/etc/bind/named.conf.options
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    networks:
      server_network:
        ipv4_address: 172.50.0.12
      client_network:
        ipv4_address: 172.51.0.12
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html/:/usr/share/nginx/html/

  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=ramhlocal
      - LDAP_DOMAIN=ramhlocal.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - LDAP_BASE_DN=dc=ramhlocal,dc=com
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=ramhlocal.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      server_network:
        ipv4_address: 172.50.0.13

  dhcp:
    image: networkboot/dhcpd
    container_name: dhcp-server
    privileged: true
    network_mode: "host"
    volumes:
      - ./DHCP/dhcpd.conf:/data/dhcpd.conf
      - ./leases:/var/lib/dhcp
    environment:
      - INTERFACES=eth0
    restart: unless-stopped

  proftpd:
    image: stilliard/pure-ftpd:hardened
    container_name: proftpd_test
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=anonymous
      - FTP_USER_PASS=anonymous
      - FTP_USER_HOME=/home/ftpusers/ftpuser
    volumes:
      - ./ftp_data:/home/ftpusers/ftpuser
    networks:
      server_network:
        ipv4_address: 172.50.0.14

  samba:
    image: dperson/samba
    container_name: samba_server
    ports:
      - "139:139"
      - "446:445"
    environment:
      - USERID=1000
      - GROUPID=1000
    command: >
      -u "admin;admin" 
      -s "public;/mount;yes;no;no;all"
    volumes:
      - ./samba_data:/mount
      - ./publico:/samba/publico
      - ./privaddo:/samba/privado
    networks:
      server_network:
        ipv4_address: 172.50.0.15

networks:
  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
  client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.51.0.0/24

volumes:
  openldap_data:
    driver: local
