
services:

  #firewall

  dns: 
    image: ubuntu/bind9
    networks:
      - server_network
    volumes:
      - ./DNS/named.conf.local:/etc/bind/named.conf.local
      - ./DNS/named.conf.options:/etc/bind/named.conf.options

  nginx:
    image: nginx:alpine
    networks:
      - server_network
      - client_network
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./nginx/html/:/usr/share/nginx/html/

  client:
    image: alpine
    networks:
      - client_network
    command: |
      sh -c "apk add curl --no-cache && curl -H 'Host: app1.com' http://nginx:80"

  dhcp:
    image: networkboot/dhcpd
    container_name: dhcp-server
    networks:
      - client_network
    privileged: true
    volumes:
      - ./dhcpd.conf:/data/dhcpd.conf:ro
      - ./leases:/data
    environment:
      - INTERFACES=eth0
    restart: unless-stopped

networks:
  server_network:
    driver: bridge
  client_network:
    driver: bridge
