
services:

  #firewall

  dns: 
    image: ubuntu/bind9
    networks:
      - server_network
    volumes:
      - ./DNS/named.conf.local:/etc/bind/named.conf.local
      - ./DNS/named.conf.options:/etc/bind/named.conf.options

  nginx:
    image: nginx:alpine
    networks:
      - server_network
      - client_network
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - ./nginx/html/:/usr/share/nginx/html/



  # docker exec -it <container_id> ldapsearch -x -H ldap://localhost:1389 -D "cn=admin,dc=example,dc=org" -w adminpassword -b "dc=example,dc=org"
  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment: 
      - LDAP_ORGANISATION=ramhlocal
      - LDAP_DOMAIN=ramhlocal.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=ramhlocal,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=ramhlocal.com.ca.crt
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - server_network

  # dhcp:
  #   image: networkboot/dhcpd
  #   container_name: dhcp-server
  #   networks:
  #     - client_network
  #   privileged: true
  #   volumes:
  #     - ./dhcpd.conf:/data/dhcpd.conf:ro
  #     - ./leases:/data
  #   environment:
  #     - INTERFACES=eth0
  #   restart: unless-stopped
  
  proftpd:
      image: stilliard/pure-ftpd:hardened
      container_name: proftpd_test
      ports:
        - "21:21"
        - "30000-30009:30000-30009"
      environment:
        - PUBLICHOST=localhost
        - FTP_USER_NAME=anonymous
        - FTP_USER_PASS=anonymous
        - FTP_USER_HOME=/home/ftpusers/ftpuser
      volumes:
        - ./ftp_data:/home/ftpusers/ftpuser 
      networks:
        - server_network
        
  samba:
    image: dperson/samba
    container_name: samba_server
    networks:
      - server_network
    ports:
      - "139:139"     
      - "445:445"     
    environment:
      - USERID=1000 
      - GROUPID=1000
    command: >
      -u "admin;admin" 
      -s "public;/mount;yes;no;no;all" 
    volumes:
      - ./samba_data:/mount
      - ./publico:/samba/publico
      - ./privaddo:/samba/privado

networks:
  server_network:
    driver: bridge
  client_network:
    driver: bridge

volumes:
  openldap_data:
    driver: local
