services:

  firewall:
    image: debian
    privileged: true
    container_name: firewall
    command: >
      bash -c "
        apt update &&
        apt install -y iptables iproute2 &&
        iptables -F &&
        iptables -P INPUT DROP &&
        iptables -P FORWARD DROP &&
        iptables -P OUTPUT ACCEPT &&
        iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT &&
        iptables -A INPUT -p tcp --dport 22 -j ACCEPT &&
        iptables -A INPUT -p tcp --dport 80 -j ACCEPT &&
        iptables -A INPUT -p tcp --dport 443 -j ACCEPT &&
        iptables -A INPUT -p tcp --dport 389 -j ACCEPT &&
        tail -f /dev/null"
    networks:
      server_network:
        ipv4_address: 172.50.0.10
      client_network:
        ipv4_address: 172.51.0.10

  dns:
    image: andyshinn/dnsmasq:2.78
    container_name: dns
    command: --no-daemon
    networks:
      client_network:
        ipv4_address: 172.51.0.11

    ports:
      - "54:53/udp"
      - "54:53/tcp"

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    networks:
      server_network:
        ipv4_address: 172.50.0.12
      client_network:
        ipv4_address: 172.51.0.12
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html/:/usr/share/nginx/html/

  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=MinhaEmpresa
      - LDAP_DOMAIN=empresa.local
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      server_network:
        ipv4_address: 172.50.0.13

  dhcpd:
    image: pnnlmiscscripts/dhcpd
    container_name: dhcpd-server
    network_mode: host
    volumes:
      - ./DHCP/dhcpd.conf:/etc/dhcp/dhcpd.conf
      - ./DHCP/dhcpd.leases:/var/lib/dhcp/dhcpd.leases
    cap_add:
      - NET_ADMIN
    environment:
      - INTERFACES=eno1
    stdin_open: true
    tty: true

  proftpd:
    image: stilliard/pure-ftpd:hardened
    container_name: proftpd_test
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=anonymous
      - FTP_USER_PASS=anonymous
      - FTP_USER_HOME=/home/ftpusers/ftpuser
    volumes:
      - ./ftp_data:/home/ftpusers/ftpuser
    networks:
      server_network:
        ipv4_address: 172.50.0.14

  samba:
    image: dperson/samba
    container_name: samba_server
    ports:
      - "139:139"
      - "446:445"
    environment:
      - USERID=1000
      - GROUPID=1000
    command: >
      -u "admin;admin" 
      -s "public;/mount;yes;no;no;all"
    volumes:
      - ./samba_data:/mount
      - ./publico:/samba/publico
      - ./privaddo:/samba/privado
    networks:
      server_network:
        ipv4_address: 172.50.0.15

networks:
  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
  client_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.51.0.0/24

volumes:
  ldap_data:
  ldap_config:
